# Generated by Django 6.0.4 on 2026-05-10 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flora', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informacion_tecnica', models.TextField(help_text='Datos adicionales que aparecen al girar la tarjeta')),
                ('estado_publicacion', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('especie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha', to='flora.especie')),
            ],
        ),
    ]
