# Generated by Django 6.0.4 on 2026-06-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interacciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='respondido',
            field=models.BooleanField(default=False),
        ),
    ]
