# Generated by Django 6.0.4 on 2026-05-10 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEspecie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('arbol', 'Árbol'), ('arbusto', 'Arbusto'), ('hierba', 'Hierba'), ('trepadora', 'Trepadora'), ('otro', 'Otro')], max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comun', models.CharField(max_length=100, unique=True)),
                ('nombre_cientifico', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='especies', to='flora.categoriaespecie')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenEspecie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='flora.especie')),
            ],
        ),
    ]
