# Generated by Django 6.0.4 on 2026-04-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EspeciePlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comun', models.CharField(max_length=100)),
                ('nombre_cientifico', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('árbol', 'Árbol'), ('arbusto', 'Arbusto'), ('hierba', 'Hierba')], max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
