# Generated by Django 6.0.4 on 2026-05-06 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('florapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEspecie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('arbol', 'Árbol'), ('arbusto', 'Arbusto'), ('hierba', 'Hierba'), ('trepadora', 'Trepadora'), ('otro', 'Otro')], max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comun', models.CharField(max_length=100, unique=True)),
                ('nombre_cientifico', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especies', to='florapp.categoriaespecie')),
            ],
        ),
        migrations.DeleteModel(
            name='EspeciePlanta',
        ),
    ]
